### ISSUE TITLE
Only show buttons for the action you have permission

### ISSUE THREAD

**Issue by SamuelRott** [jfalxa/arbela#4]
Actual: 
everybody can see all buttons (normal user can see delete board button) even when they don't have permission for the action.

Expected: 
Only show button i have permission for.

Suggestion:
Create ALLOWED_ACTIONS array in the back end (sorry i don't know how) and create the front-end logic show/hide on it

**Comment by jfalxa** [comment]
Done for member menu in https://github.com/jfalxa/arbela/commit/9c6555933cb7cb2fd1ae9e7a1b0f8ad5ec8d6193

**Comment by jfalxa** [comment]
Also done for:
- board edit button (only for owner)
- link votes (only for allowed users + non-voters)
- link share (only for auth users)
- link edit (only for author)
- Post link and Created board in Navigation (only for auth users)
